call plug#begin()

Plug 'preservim/nerdtree'
Plug 'itchyny/lightline.vim'
Plug 'lifepillar/vim-solarized8'
Plug 'arzg/vim-colors-xcode'

call plug#end()

set laststatus=2
set noshowmode
set softtabstop=4
set shiftwidth=4
set expandtab
set incsearch
set ignorecase
set smartcase
set ruler
set showmode
set viminfo=%,'50,\"100,:100,n~/.viminfo
set autoindent
set backspace=2

let g:lightline = {
      \ 'colorscheme': 'wombat',
      \ }

syntax enable
colorscheme solarized8
set termguicolors

map <silent> <C-n> :NERDTreeToggle<CR>
